let
  Source = AzureResourceGraph.Query("ResourceContainers | where type == 'microsoft.resources/subscriptions'", null, null, null, [resultTruncated = true]),
  #"Transform columns" = Table.TransformColumnTypes(Source, {{"id", type text}, {"name", type text}, {"type", type text}, {"tenantId", type text}, {"kind", type any}, {"location", type any}, {"resourceGroup", type any}, {"subscriptionId", type text}, {"managedBy", type any}, {"sku", type any}, {"plan", type any}, {"properties", type any}, {"tags", type any}, {"identity", type any}, {"zones", type any}, {"extendedLocation", type any}}),
  #"Removed other columns" = Table.SelectColumns(#"Transform columns", {"name", "subscriptionId", "tags"}),
  #"Reordered columns" = Table.ReorderColumns(#"Removed other columns", {"subscriptionId", "name", "tags"}),
  #"Expanded tags" = Table.ExpandRecordColumn(#"Reordered columns", "tags", {"Owner", "Cost Centre", "Approver"}, {"tags.Owner", "tags.Cost Centre", "tags.Approver"}),
  #"Transform columns 1" = Table.TransformColumnTypes(#"Expanded tags", {{"tags.Owner", type text}, {"tags.Cost Centre", type text}, {"tags.Approver", type text}})
in
  #"Transform columns 1"
